name: 'Nightwatch AI Audit'
description: 'Run AI-powered codebase audits using batch API (50% off)'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  mode:
    description: 'submit (send to batch API) or retrieve (get results)'
    required: true
    default: 'submit'
  focus:
    description: 'Focus area to audit. Defaults to today''s schedule.'
    required: false
  config:
    description: 'Path to nightwatch.yml config file.'
    required: false
    default: 'nightwatch.yml'
  anthropic-api-key:
    description: 'Anthropic API key'
    required: false
  telegram-bot-token:
    description: 'Telegram bot token for notifications'
    required: false
  telegram-chat-id:
    description: 'Telegram chat ID for notifications'
    required: false
  github-token:
    description: 'GitHub token for creating issues'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install nightwatch
      shell: bash
      run: pip install git+https://github.com/atriumn/nightwatch.git

    - name: Restore pending batch (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/restore@v4
      with:
        path: .nightwatch/pending-batch.json
        key: nightwatch-pending-will-not-match
        restore-keys: nightwatch-pending-

    - name: Restore last-retrieved guard (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/restore@v4
      with:
        path: .nightwatch/last-retrieved.json
        key: nightwatch-retrieved-will-not-match
        restore-keys: nightwatch-retrieved-

    - name: Run nightwatch
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        TELEGRAM_BOT_TOKEN: ${{ inputs.telegram-bot-token }}
        TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ "${{ inputs.mode }}" = "submit" ]; then
          ARGS="--config ${{ inputs.config }}"
          if [ -n "${{ inputs.focus }}" ]; then
            ARGS="$ARGS --focus ${{ inputs.focus }}"
          fi
          nightwatch submit $ARGS
        else
          nightwatch retrieve --config ${{ inputs.config }}
        fi

    - name: Cache pending batch (submit mode)
      if: inputs.mode == 'submit'
      uses: actions/cache/save@v4
      with:
        path: .nightwatch/pending-batch.json
        key: nightwatch-pending-${{ github.run_id }}

    - name: Cache last-retrieved guard (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/save@v4
      with:
        path: .nightwatch/last-retrieved.json
        key: nightwatch-retrieved-${{ github.run_id }}

    - name: Upload reports
      uses: actions/upload-artifact@v4
      if: inputs.mode == 'retrieve'
      with:
        name: nightwatch-reports
        path: .nightwatch/reports/
        retention-days: 30
