name: 'Noxaudit'
description: 'Nightly AI-powered codebase audits with rotating focus areas'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  mode:
    description: 'submit (send to batch API) or retrieve (get results)'
    required: true
    default: 'submit'
  focus:
    description: 'Focus area to audit. Defaults to today''s schedule.'
    required: false
  config:
    description: 'Path to noxaudit.yml config file.'
    required: false
    default: 'noxaudit.yml'
  anthropic-api-key:
    description: 'Anthropic API key'
    required: false
  telegram-bot-token:
    description: 'Telegram bot token for notifications'
    required: false
  telegram-chat-id:
    description: 'Telegram chat ID for notifications'
    required: false
  github-token:
    description: 'GitHub token for creating issues'
    required: false
    default: ${{ github.token }}
  format:
    description: 'Output format: markdown (default) or sarif (for GitHub Code Scanning upload)'
    required: false
    default: 'markdown'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning (requires format: sarif and write security-events permission)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install noxaudit
      shell: bash
      run: pip install git+https://github.com/atriumn/noxaudit.git

    - name: Restore pending batch (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/restore@v4
      with:
        path: .noxaudit/pending-batch.json
        key: noxaudit-pending-will-not-match
        restore-keys: noxaudit-pending-

    - name: Restore last-retrieved guard (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/restore@v4
      with:
        path: .noxaudit/last-retrieved.json
        key: noxaudit-retrieved-will-not-match
        restore-keys: noxaudit-retrieved-

    - name: Run noxaudit
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
        TELEGRAM_BOT_TOKEN: ${{ inputs.telegram-bot-token }}
        TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        if [ "${{ inputs.mode }}" = "submit" ]; then
          ARGS="--config ${{ inputs.config }}"
          if [ -n "${{ inputs.focus }}" ]; then
            ARGS="$ARGS --focus ${{ inputs.focus }}"
          fi
          noxaudit submit $ARGS
        else
          noxaudit retrieve --config ${{ inputs.config }} --format ${{ inputs.format }}
        fi

    - name: Cache pending batch (submit mode)
      if: inputs.mode == 'submit'
      uses: actions/cache/save@v4
      with:
        path: .noxaudit/pending-batch.json
        key: noxaudit-pending-${{ github.run_id }}

    - name: Cache last-retrieved guard (retrieve mode)
      if: inputs.mode == 'retrieve'
      uses: actions/cache/save@v4
      with:
        path: .noxaudit/last-retrieved.json
        key: noxaudit-retrieved-${{ github.run_id }}

    - name: Upload reports
      uses: actions/upload-artifact@v4
      if: inputs.mode == 'retrieve'
      with:
        name: noxaudit-reports
        path: .noxaudit/reports/
        retention-days: 30

    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.mode == 'retrieve' && inputs.upload-sarif == 'true'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: .noxaudit/reports/
        category: noxaudit
